bazel_dep(name = "aspect_rules_js", version = "3.3.1")
bazel_dep(name = "bazel_lib", version = "3.5.0")
bazel_dep(name = "bazelrc-preset.bzl", version = "1.9.2")
bazel_dep(name = "platforms", version = "1.1.0")
bazel_dep(name = "rules_img", version = "0.3.6")
bazel_dep(name = "rules_java", version = "9.7.0")
bazel_dep(name = "rules_pkg", version = "1.1.0")
bazel_dep(name = "rules_shell", version = "0.8.0")

npm = use_extension("@aspect_rules_js//npm:extensions.bzl", "npm")
npm.npm_translate_lock(
    name = "npm",
    pnpm_lock = "//:pnpm-lock.yaml",
)
use_repo(npm, "npm")

# Allows developers to use the matching pnpm version, for example:
# bazel run -- @pnpm --dir $(pwd) install
pnpm = use_extension("@aspect_rules_js//npm:extensions.bzl", "pnpm", dev_dependency = True)
use_repo(pnpm, "pnpm")

pull = use_repo_rule("@rules_img//img:pull.bzl", "pull")

# renovate-handled:
pull(
    name = "lighttpd_image",
    digest = "sha256:b3bcd07d219fd54625b79613102d8d1f9ca45bb2246d9c9f767a482f44573ebf",
    registry = "ghcr.io",
    repository = "avm99963/lighttpd",
    tag = "latest",
)

# As per
# https://github.com/google/copybara/blob/eb3a1fdb338a90be30cc8b457edc51f9aed268a8/README.md#using-pre-built-copybara-in-bazel.
http_jar = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_jar")

# TODO: Autoupdate Copybara via Renovate.
http_jar(
    name = "com_github_google_copybara",
    # Fill in from https://github.com/google/copybara/releases/download/[version]/copybara_deploy.jar.sha256
    sha256 = "3a073629633db5757aa9649b9935b135fdf3d70dd554ce7732249018d803f0b1",
    urls = ["https://github.com/google/copybara/releases/download/v20260406/copybara_deploy.jar"],
)
