package timezone

import (
	"log"
	"strings"
	"time"
)

// iataToTZ maps Wizz Air airport IATA codes to IANA timezone identifiers.
var iataToTZ = map[string]string{
	"ABZ": "Europe/London",
	"AES": "Europe/Oslo",
	"AGA": "Africa/Casablanca",
	"AGP": "Europe/Madrid",
	"AHO": "Europe/Rome",
	"ALC": "Europe/Madrid",
	"AMM": "Asia/Amman",
	"AOI": "Europe/Rome",
	"ARN": "Europe/Stockholm",
	"ATH": "Europe/Athens",
	"AUH": "Asia/Dubai",
	"AYT": "Europe/Istanbul",
	"BBU": "Europe/Bucharest",
	"BCM": "Europe/Bucharest",
	"BCN": "Europe/Madrid",
	"BDS": "Europe/Rome",
	"BEG": "Europe/Belgrade",
	"BER": "Europe/Berlin",
	"BGO": "Europe/Oslo",
	"BGY": "Europe/Rome",
	"BHX": "Europe/London",
	"BIO": "Europe/Madrid",
	"BLL": "Europe/Copenhagen",
	"BLQ": "Europe/Rome",
	"BNX": "Europe/Sarajevo",
	"BOD": "Europe/Paris",
	"BOJ": "Europe/Sofia",
	"BRI": "Europe/Rome",
	"BSL": "Europe/Paris",
	"BTS": "Europe/Bratislava",
	"BUD": "Europe/Budapest",
	"BVA": "Europe/Paris",
	"CDT": "Europe/Madrid",
	"CFU": "Europe/Athens",
	"CGN": "Europe/Berlin",
	"CHQ": "Europe/Athens",
	"CIA": "Europe/Rome",
	"CIY": "Europe/Rome",
	"CLJ": "Europe/Bucharest",
	"CND": "Europe/Bucharest",
	"CPH": "Europe/Copenhagen",
	"CRA": "Europe/Bucharest",
	"CRL": "Europe/Brussels",
	"CTA": "Europe/Rome",
	"DBV": "Europe/Zagreb",
	"DEB": "Europe/Budapest",
	"DLM": "Europe/Istanbul",
	"DTM": "Europe/Berlin",
	"DXB": "Asia/Dubai",
	"EFL": "Europe/Athens",
	"EIN": "Europe/Amsterdam",
	"ESB": "Europe/Istanbul",
	"EVN": "Asia/Yerevan",
	"FAO": "Europe/Lisbon",
	"FCO": "Europe/Rome",
	"FDH": "Europe/Berlin",
	"FKB": "Europe/Berlin",
	"FMM": "Europe/Berlin",
	"FNC": "Atlantic/Madeira",
	"FUE": "Atlantic/Canary",
	"GDN": "Europe/Warsaw",
	"GHV": "Europe/Bucharest",
	"GLA": "Europe/London",
	"GNB": "Europe/Paris",
	"GOA": "Europe/Rome",
	"GOT": "Europe/Stockholm",
	"GRX": "Europe/Madrid",
	"GYD": "Asia/Baku",
	"HAM": "Europe/Berlin",
	"HAU": "Europe/Oslo",
	"HBE": "Africa/Cairo",
	"HER": "Europe/Athens",
	"HHN": "Europe/Berlin",
	"HRG": "Africa/Cairo",
	"IAS": "Europe/Bucharest",
	"IBZ": "Europe/Madrid",
	"INI": "Europe/Belgrade",
	"IST": "Europe/Istanbul",
	"JED": "Asia/Riyadh",
	"JMK": "Europe/Athens",
	"JSI": "Europe/Athens",
	"JTR": "Europe/Athens",
	"KEF": "Atlantic/Reykjavik",
	"KLX": "Europe/Athens",
	"KRK": "Europe/Warsaw",
	"KSC": "Europe/Bratislava",
	"KTW": "Europe/Warsaw",
	"KUN": "Europe/Vilnius",
	"KUT": "Asia/Tbilisi",
	"LBA": "Europe/London",
	"LCA": "Asia/Nicosia",
	"LEI": "Europe/Madrid",
	"LGW": "Europe/London",
	"LIS": "Europe/Lisbon",
	"LJU": "Europe/Ljubljana",
	"LMP": "Europe/Rome",
	"LPA": "Atlantic/Canary",
	"LPL": "Europe/London",
	"LTN": "Europe/London",
	"LUZ": "Europe/Warsaw",
	"LWN": "Asia/Yerevan",
	"LYS": "Europe/Paris",
	"MAD": "Europe/Madrid",
	"MAH": "Europe/Madrid",
	"MLA": "Europe/Malta",
	"MLH": "Europe/Paris",
	"MMX": "Europe/Stockholm",
	"MST": "Europe/Amsterdam",
	"MXP": "Europe/Rome",
	"NAP": "Europe/Rome",
	"NCE": "Europe/Paris",
	"NUE": "Europe/Berlin",
	"NYO": "Europe/Stockholm",
	"OHD": "Europe/Skopje",
	"OLB": "Europe/Rome",
	"OMR": "Europe/Bucharest",
	"OPO": "Europe/Lisbon",
	"ORY": "Europe/Paris",
	"OSL": "Europe/Oslo",
	"OTP": "Europe/Bucharest",
	"OVD": "Europe/Madrid",
	"PDV": "Europe/Sofia",
	"PEG": "Europe/Rome",
	"PFO": "Asia/Nicosia",
	"PLQ": "Europe/Vilnius",
	"PMI": "Europe/Madrid",
	"PMO": "Europe/Rome",
	"POZ": "Europe/Warsaw",
	"PRG": "Europe/Prague",
	"PRN": "Europe/Belgrade",
	"PSA": "Europe/Rome",
	"PSR": "Europe/Rome",
	"RAK": "Africa/Casablanca",
	"RDO": "Europe/Warsaw",
	"RHO": "Europe/Athens",
	"RJK": "Europe/Zagreb",
	"RMF": "Africa/Cairo",
	"RMI": "Europe/Rome",
	"RMO": "Europe/Chisinau",
	"RZE": "Europe/Warsaw",
	"SBZ": "Europe/Bucharest",
	"SCQ": "Europe/Madrid",
	"SCV": "Europe/Bucharest",
	"SDR": "Europe/Madrid",
	"SJJ": "Europe/Sarajevo",
	"SKG": "Europe/Athens",
	"SKP": "Europe/Skopje",
	"SOF": "Europe/Sofia",
	"SPU": "Europe/Zagreb",
	"SPX": "Africa/Cairo",
	"SSH": "Africa/Cairo",
	"STR": "Europe/Berlin",
	"SUF": "Europe/Rome",
	"SUJ": "Europe/Bucharest",
	"SVG": "Europe/Oslo",
	"SVQ": "Europe/Madrid",
	"SZY": "Europe/Warsaw",
	"SZZ": "Europe/Warsaw",
	"TAT": "Europe/Bratislava",
	"TFS": "Atlantic/Canary",
	"TGD": "Europe/Podgorica",
	"TGM": "Europe/Bucharest",
	"TIA": "Europe/Tirane",
	"TKU": "Europe/Helsinki",
	"TLL": "Europe/Tallinn",
	"TLV": "Asia/Tel_Aviv",
	"TOS": "Europe/Oslo",
	"TRD": "Europe/Oslo",
	"TRF": "Europe/Oslo",
	"TRN": "Europe/Rome",
	"TRS": "Europe/Rome",
	"TSF": "Europe/Rome",
	"TSR": "Europe/Bucharest",
	"TZL": "Europe/Sarajevo",
	"VAR": "Europe/Sofia",
	"VCE": "Europe/Rome",
	"VLC": "Europe/Madrid",
	"VNO": "Europe/Vilnius",
	"VRN": "Europe/Rome",
	"WAW": "Europe/Warsaw",
	"WMI": "Europe/Warsaw",
	"WRO": "Europe/Warsaw",
	"ZAD": "Europe/Zagreb",
	"ZAZ": "Europe/Madrid",
	"ZTH": "Europe/Athens",
}

func getTimezoneName(iata string, fallbackTZ string) string {
	code := strings.ToUpper(strings.TrimSpace(iata))
	if tz, ok := iataToTZ[code]; ok {
		return tz
	}
	if fallbackTZ == "" {
		fallbackTZ = "Europe/Warsaw"
	}
	log.Printf("WARNING: Unknown airport IATA code %q; falling back to timezone %q", iata, fallbackTZ)
	return fallbackTZ
}

// GetLocation loads and returns the *time.Location for a given IATA airport code,
// falling back to fallbackTZ if unknown or failed to load.
func GetLocation(iata string, fallbackTZ string) *time.Location {
	tzName := getTimezoneName(iata, fallbackTZ)
	loc, err := time.LoadLocation(tzName)
	if err != nil {
		log.Printf("ERROR: Failed to load location %q for IATA %q: %v; falling back to UTC", tzName, iata, err)
		return time.UTC
	}
	return loc
}
